### ISSUE TITLE
Graph showed negative number (-900) on China Daily increases in Recoveries around date 88 from 1/22/2020 ?

### ISSUE THREAD

**Issue by MilSix** [therealcyberlord/coronavirus_visualization_and_prediction#3]
Hi, I wasn't sure how to interpret the negative number that showed on about date 88 of your graph with title "China Daily increases in Recoveries" Can you explain why? 

![image](https://user-images.githubusercontent.com/33041085/85912002-052f1c00-b7f7-11ea-9fb3-e67b5f10ac9e.png)

**Comment by therealcyberlord** [comment]
I am guessing that might be a mistake from counting.

**Comment by MilSix** [comment]
from data or from your method? if from data  do you thing could they be data in data set from JHU?

**Comment by MilSix** [comment]
Similar issue I found with graph for "Italy Daily Increases in Death" yesterday or the day before 
![image](https://user-images.githubusercontent.com/33041085/85912343-d2d2ee00-b7f9-11ea-9b50-a13a81509f0e.png)

**Comment by therealcyberlord** [comment]
It is from JHU. My code is simply finding the daily changes. Thanks for letting me know. I appreciate your feedback.
