### ISSUE TITLE
Question on : plot_predictions(adjusted_dates, world_cases, linear_pred, 'Polynomial Regression Predictions', 'orange')

### ISSUE THREAD

**Issue by MilSix** [therealcyberlord/coronavirus_visualization_and_prediction#5]
Just wonder why did you pick "Polynomial Regression Prediction"  over "Linear Regression Prediction" ? Won't Linear Regression Prediction will fit better with actual world_cases?
![image](https://user-images.githubusercontent.com/33041085/85913377-45e06280-b802-11ea-9505-bd3e0b762ea5.png)

Not sure if I'm missing something but from the graph output ...your predictic values on the first 28 days are too far away from actual world cases value.

**Comment by therealcyberlord** [comment]
The training data started from a later date since the model struggled to capture the entire time span. Sorry for the confusion.

**Comment by therealcyberlord** [comment]
The forecast included earlier days which the model never saw in training.
